# Edit node configs


- name: Turn off write-behind
  hosts: localhost
  gather_facts: False
  vars_files:
    - ansible_vars.yml
  tags:
    - no_wb
  tasks:
    - name: Get contents of node's conf files
      shell: cat "{{ conf_path | expanduser }}"/conf/{{item}}-cluster.yaml
      register: all_conf
      with_items: "{{ hostvars[inventory_hostname].groups.tag_Name_nuchain_server }}"

    - name: Set writeBehind to False
      template:
        src: templates/conf.j2
        dest: "{{ conf_path | expanduser }}/conf/{{item.item}}-cluster.yaml"
      vars:
        conf: "{{item.stdout | from_yaml | combine({'pactPersist': {'writeBehind': false}}, recursive=True)}}"
      with_items: "{{ all_conf.results }}"


- name: Turn off all PactPersist logging
  hosts: localhost
  gather_facts: False
  tags:
    - no_pactPersist_log
  vars_files:
    - ansible_vars.yml
  tasks:
    - name: Get contents of node's conf files
      shell: cat "{{ conf_path | expanduser }}"/conf/{{item}}-cluster.yaml
      register: all_conf
      with_items: "{{ hostvars[inventory_hostname].groups.tag_Name_nuchain_server }}"

    - name: Exclude DEBUG statements from PactPersist in logRules
      template:
        src: templates/conf.j2
        dest: "{{ conf_path | expanduser }}/conf/{{item.item}}-cluster.yaml"
      vars:
        pactPersist: {'PactPersist': {'include': null, 'enable': null, 'exclude': [DEBUG]}}
        conf: "{{item.stdout | from_yaml | combine({'logRules': pactPersist}, recursive=True)}}"
      with_items: "{{ all_conf.results }}"


- name: Turn off all debugging
  hosts: localhost
  gather_facts: False
  tags:
    - no_debug
  vars_files:
    - ansible_vars.yml
  tasks:
    - name: Get contents of node's conf files
      shell: cat "{{ conf_path | expanduser }}"/conf/{{item}}-cluster.yaml
      register: all_conf
      with_items: "{{ hostvars[inventory_hostname].groups.tag_Name_nuchain_server }}"

    - name: Set enableDebug to false
      template:
        src: templates/conf.j2
        dest: "{{ conf_path | expanduser }}/conf/{{item.item}}-cluster.yaml"
      vars:
        conf: "{{item.stdout | from_yaml | combine({'enableDebug': false}, recursive=True)}}"
      with_items: "{{ all_conf.results }}"


# ---- CHANGE BACKEND  ----

- name: Use in-memory backend
  hosts: localhost
  gather_facts: False
  tags:
    - inmem
  vars_files:
    - ansible_vars.yml
  tasks:
    - name: Get contents of node's conf files
      shell: cat "{{ conf_path | expanduser }}"/conf/{{item}}-cluster.yaml
      register: all_conf
      with_items: "{{ hostvars[inventory_hostname].groups.tag_Name_nuchain_server }}"

    - name: Set PactPersist backend to use INMEM
      template:
        src: templates/conf.j2
        dest: "{{ conf_path | expanduser }}/conf/{{item.item}}-cluster.yaml"
      vars:
        inMem: {'config': null, 'type': INMEM}
        conf: "{{item.stdout | from_yaml | combine({'pactPersist': {'backend': inMem}}, recursive=True)}}"
      with_items: "{{ all_conf.results }}"
